### ISSUE TITLE
Server sometimes crashes when game ends

### ISSUE THREAD

**Issue by WilliamDann** [WilliamDann/minesweeper-royale#11]
When the game ends and the user doesn't click the new game button the server can crash with the following error:

return rect.x <= point.x && point.x < rect.x + rect.w && rect.y <= point.y && point.y < rect.y + rect.h;
                    ^
TypeError: Cannot read property 'x' of undefined
    at pointInRect (C:\Users\wcdan\Documents\CodeDay\server\routes\socket.js:24:14)
    at WebSocket.<anonymous> (C:\Users\wcdan\Documents\CodeDay\server\routes\socket.js:162:11)
    at WebSocket.emit (events.js:188:13)
    at Receiver.receiverOnMessage (C:\Users\wcdan\Documents\CodeDay\server\node_modules\ws\lib\websocket.js:720:20)
    at Receiver.emit (events.js:188:13)
    at Receiver.dataMessage (C:\Users\wcdan\Documents\CodeDay\server\node_modules\ws\lib\receiver.js:414:14)
    at Receiver.getData (C:\Users\wcdan\Documents\CodeDay\server\node_modules\ws\lib\receiver.js:346:17)
    at Receiver.startLoop (C:\Users\wcdan\Documents\CodeDay\server\node_modules\ws\lib\receiver.js:133:22)
    at Receiver._write (C:\Users\wcdan\Documents\CodeDay\server\node_modules\ws\lib\receiver.js:69:10)    at doWrite (_stream_writable.js:415:12)

**Comment by WilliamDann** [comment]
@ottomated What if we detected when the tab is closed and had the client send a message saying they have disconnected?

We could use `onunload` or `onbeforeunload` to do that easily.

**Comment by ottomated** [comment]
Not the best idea, I'd think this should be solved given that I do detect a websocket close event, so that's where we should go for troubleshooting.

**Comment by WilliamDann** [comment]
This could be the fault of the flood fill in minesweeper.js. The following error occurs when the user does not close the program 'correctly'.

C:\Users\wcdan\Documents\Projects\finished\CodeDay\backend\minesweeper.js:128
                function recurse(x, y) {
                                ^

RangeError: Maximum call stack size exceeded
    at recurse (C:\Users\wcdan\Documents\Projects\finished\CodeDay\backend\minesweeper.js:128:19)
    at recurse (C:\Users\wcdan\Documents\Projects\finished\CodeDay\backend\minesweeper.js:136:7)
    at recurse (C:\Users\wcdan\Documents\Projects\finished\CodeDay\backend\minesweeper.js:136:7)
    at recurse (C:\Users\wcdan\Documents\Projects\finished\CodeDay\backend\minesweeper.js:136:7)
    at recurse (C:\Users\wcdan\Documents\Projects\finished\CodeDay\backend\minesweeper.js:136:7)
    at recurse (C:\Users\wcdan\Documents\Projects\finished\CodeDay\backend\minesweeper.js:136:7)
    at recurse (C:\Users\wcdan\Documents\Projects\finished\CodeDay\backend\minesweeper.js:136:7)
    at recurse (C:\Users\wcdan\Documents\Projects\finished\CodeDay\backend\minesweeper.js:136:7)
    at recurse (C:\Users\wcdan\Documents\Projects\finished\CodeDay\backend\minesweeper.js:136:7)
    at recurse (C:\Users\wcdan\Documents\Projects\finished\CodeDay\backend\minesweeper.js:136:7)
 
I will look into this more.
